name: CheckPR

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm exec tsc
    - run: node dist/cli.js
