name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm exec tsc
    - run: node dist/cli.js
    - name: Upload schema
      uses: ncipollo/release-action@v1
      with:
        artifacts: "schema.min.json,schema.jsonl"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
